In [1]:
import numpy as np

In [2]:
from scipy import stats

In [3]:
import pandas as pd

In [4]:
dataset=pd.read_csv(r"C:\Users\user\Desktop\covid_impact_on_airport_traffic.csv")
dataset

,AggregationMethod,Date,Version,AirportName,PercentOfBaseline,Centroid,City,State,ISO_3166_2,Country,Geography
0,Daily,2020-07-05,1.0,Kingsford Smith,52,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
1,Daily,2020-05-28,1.0,Kingsford Smith,61,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
2,Daily,2020-05-07,1.0,Kingsford Smith,62,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
3,Daily,2020-06-24,1.0,Kingsford Smith,58,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
4,Daily,2020-08-05,1.0,Kingsford Smith,20,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
...,...,...,...,...,...,...,...,...,...,...,...
5931,Daily,2020-06-15,1.0,Seattle-Tacoma International,64,POINT(-122.308661576118 47.4505828917119),SeaTac,Washington,US-WA,United States of America (the),"POLYGON((-122.297594547272 47.434474106872, -1..."
5932,Daily,2020-10-15,1.0,Seattle-Tacoma International,74,POINT(-122.308661576118 47.4505828917119),SeaTac,Washington,US-WA,United States of America (the),"POLYGON((-122.297594547272 47.434474106872, -1..."
5933,Daily,2020-04-01,1.0,Seattle-Tacoma International,65,POINT(-122.308661576118 47.4505828917119),SeaTac,Washington,US-WA,United States of America (the),"POLYGON((-122.297594547272 47.434474106872, -1..."
5934,Daily,2020-05-12,1.0,Seattle-Tacoma International,65,POINT(-122.308661576118 47.4505828917119),SeaTac,Washington,US-WA,United States of America (the),"POLYGON((-122.297594547272 47.434474106872, -1..."
5935,Daily,2020-10-11,1.0,Seattle-Tacoma International,57,POINT(-122.308661576118 47.4505828917119),SeaTac,Washington,US-WA,United States of America (the),"POLYGON((-122.297594547272 47.434474106872, -1..."

In [5]:
dataset.head()

,AggregationMethod,Date,Version,AirportName,PercentOfBaseline,Centroid,City,State,ISO_3166_2,Country,Geography
0,Daily,2020-07-05,1.0,Kingsford Smith,52,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
1,Daily,2020-05-28,1.0,Kingsford Smith,61,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
2,Daily,2020-05-07,1.0,Kingsford Smith,62,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
3,Daily,2020-06-24,1.0,Kingsford Smith,58,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
4,Daily,2020-08-05,1.0,Kingsford Smith,20,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."

In [6]:
dataset.shape

(5936, 11)

In [7]:
dataset.columns

Index(['AggregationMethod', 'Date', 'Version', 'AirportName',
       'PercentOfBaseline', 'Centroid', 'City', 'State', 'ISO_3166_2',
       'Country', 'Geography'],
      dtype='object')

In [8]:
dataset.info

<bound method DataFrame.info of      AggregationMethod        Date  Version                    AirportName  \
0                Daily  2020-07-05      1.0                Kingsford Smith
1                Daily  2020-05-28      1.0                Kingsford Smith
2                Daily  2020-05-07      1.0                Kingsford Smith
3                Daily  2020-06-24      1.0                Kingsford Smith
4                Daily  2020-08-05      1.0                Kingsford Smith
...                ...         ...      ...                            ...
5931             Daily  2020-06-15      1.0  Seattle-Tacoma International
5932             Daily  2020-10-15      1.0  Seattle-Tacoma International
5933             Daily  2020-04-01      1.0  Seattle-Tacoma International
5934             Daily  2020-05-12      1.0  Seattle-Tacoma International
5935             Daily  2020-10-11      1.0  Seattle-Tacoma International

      PercentOfBaseline                                   Centroid    City  \
0                    52  POINT(151.180087713813 -33.9459774986125)  Sydney
1                    61  POINT(151.180087713813 -33.9459774986125)  Sydney
2                    62  POINT(151.180087713813 -33.9459774986125)  Sydney
3                    58  POINT(151.180087713813 -33.9459774986125)  Sydney
4                    20  POINT(151.180087713813 -33.9459774986125)  Sydney
...                 ...                                        ...     ...
5931                 64  POINT(-122.308661576118 47.4505828917119)  SeaTac
5932                 74  POINT(-122.308661576118 47.4505828917119)  SeaTac
5933                 65  POINT(-122.308661576118 47.4505828917119)  SeaTac
5934                 65  POINT(-122.308661576118 47.4505828917119)  SeaTac
5935                 57  POINT(-122.308661576118 47.4505828917119)  SeaTac

                State ISO_3166_2                         Country  \
0     New South Wales         AU                       Australia
1     New South Wales         AU                       Australia
2     New South Wales         AU                       Australia
3     New South Wales         AU                       Australia
4     New South Wales         AU                       Australia
...               ...        ...                             ...
5931       Washington      US-WA  United States of America (the)
5932       Washington      US-WA  United States of America (the)
5933       Washington      US-WA  United States of America (the)
5934       Washington      US-WA  United States of America (the)
5935       Washington      US-WA  United States of America (the)

                                              Geography
0     POLYGON((151.164354085922 -33.9301772341877, 1...
1     POLYGON((151.164354085922 -33.9301772341877, 1...
2     POLYGON((151.164354085922 -33.9301772341877, 1...
3     POLYGON((151.164354085922 -33.9301772341877, 1...
4     POLYGON((151.164354085922 -33.9301772341877, 1...
...                                                 ...
5931  POLYGON((-122.297594547272 47.434474106872, -1...
5932  POLYGON((-122.297594547272 47.434474106872, -1...
5933  POLYGON((-122.297594547272 47.434474106872, -1...
5934  POLYGON((-122.297594547272 47.434474106872, -1...
5935  POLYGON((-122.297594547272 47.434474106872, -1...

[5936 rows x 11 columns]>

In [9]:
dataset.describe()

       Version  PercentOfBaseline
count   5936.0        5936.000000
mean       1.0          65.581705
std        0.0          21.985070
min        1.0           0.000000
25%        1.0          52.000000
50%        1.0          66.000000
75%        1.0          82.000000
max        1.0         100.000000

In [10]:
dataset.duplicated().sum()

0

In [11]:
dataset.isnull().sum()

AggregationMethod    0
Date                 0
Version              0
AirportName          0
PercentOfBaseline    0
Centroid             0
City                 0
State                0
ISO_3166_2           0
Country              0
Geography            0
dtype: int64